channels:
- conda-forge
dependencies:
- bidict =0.23.1
- h5py =3.14.0
- hatchling =1.27.0
- hatch-vcs =0.5.0
- mpi4py =4.0.1
- numpy =2.3.1
- pygtrie =2.5.0
- pyiron_snippets =0.2.0
- python >=3.11,<3.14
