# This runs jobs which pyiron modules should run on release
# This job runs on pull requests and does not actually publish anything to pypi
# It is useful for debugging new build recipes
# To actually release, change the `on` and `publish-to-pypi` fields
name: Release

on:
  pull_request:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/hatch-release.yml@actions-4.0.9
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower_bound.yml'
      upper-bound-yaml: '.ci_support/upper_bound.yml'
      publish-to-pypi: ${{ github.event_name == 'release' && github.event.action == 'published' }}